services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_DOCKER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DOCKER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DOCKER_DB}
    ports:
      - "5433:5432"
    networks:
      - horse-net
    volumes:
      - db_data:/var/lib/postgresql/data

  spring:
    build: ./
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8080:8090"
    networks:
      - horse-net

volumes:
  db_data:

networks:
  horse-net:
    driver: bridge