services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_DOCKER_USER:-${POSTGRES_USER:-postgres}}
      POSTGRES_PASSWORD: ${POSTGRES_DOCKER_PASSWORD:-${POSTGRES_PASSWORD:-MyPassword123!}}
      POSTGRES_DB: ${POSTGRES_DOCKER_DB:-${POSTGRES_DB:-horse-trust}}
    ports:
      - "5433:5432"
    networks:
      - horse-net
    volumes:
      - db_data:/var/lib/postgresql/data

  spring:
    image: ${BACKEND_IMAGE}
    depends_on:
      - database
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-database}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DOCKER_DB:-${POSTGRES_DB:-horse-trust}}
      POSTGRES_USER: ${POSTGRES_DOCKER_USER:-${POSTGRES_USER:-postgres}}
      POSTGRES_PASSWORD: ${POSTGRES_DOCKER_PASSWORD:-${POSTGRES_PASSWORD:-MyPassword123!}}
      POSTGRES_DOCKER_URL: ${POSTGRES_DOCKER_URL:-jdbc:postgresql://${POSTGRES_HOST:-database}:${POSTGRES_PORT:-5432}/${POSTGRES_DOCKER_DB:-${POSTGRES_DB:-horse-trust}}}
      PORT: ${PORT:-8090}
    ports:
      - "8070:8090"
    networks:
      - horse-net

volumes:
  db_data:

networks:
  horse-net:
    driver: bridge