version: '3.8'

services:
  database:
    image: postgres:16
    container_name: horsetrust-backend-database-1
    environment:
      # These match the variables generated in the Jenkins 'deployApp' function
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - horse-net
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring:
    image: ${BACKEND_IMAGE}
    container_name: horsetrust-backend-spring-1
    depends_on:
      database:
        condition: service_healthy
    environment:
      # Spring Boot 3 automatically maps these to the DataSource
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      # Application specific secrets
      SECRET_KEY: ${SECRET_KEY}
      SERVER_PORT: 8090
    ports:
      - "8070:8090"
    networks:
      - horse-net
    restart: always

volumes:
  db_data:

networks:
  horse-net:
    driver: bridge